import Link from "next/link";
import NextImage from "next/image";

import Text from "./text";


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


const data = [
  {
    "title": "Game day",
    "image": '/game.jpg',
    "description": " There is no experience like watching ISU football team loose a match."
  },
  {
    "title": "Lied Gym",
    "image": '/lied.jpg',
    "description": "U want basketball, uve got basketball, 20 and dats just in one gym."
  },
  {
    "title": "Memorial Union",
    "image": '/mu.jpg',
    "description": "The Curse: U step on it, u fail ur next exam."
  },
  {
    "title": "Gerdin kingland Hub",
    "image": '/gerdin-kingland.jpg',
    "description": "A hub for studying in the business building. With a design that really inspires learning."
  },
  {
    "title": "State Gym",
    "image": '/gym.jpg',
    "description": " Just watch as you slowly become a gym rat when you come to ISU. "
  },
  {
    "title": "Horticulture building",
    "image": '/horti.jpg',
    "description": "There is just a freshness about this building. It really does have a calming effect. You can try it and thank me."
  },
  {
    "title": "Memorial Union",
    "image": '/mu.jpg',
    "description": "The Curse: U step on it, u fail ur next exam."
  },
  {
    "title": "Gerdin kingland Hub",
    "image": '/gerdin-kingland.jpg',
    "description": "A hub for studying in the business building. With a design that really inspires learning."
  },
]


export default function Home() {
  return (
    <>
      <header className='fixed z-10 top-0 w-full shadow-md border-gray-200/50 border-b bg-inherit'> 
        <nav className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto py-2 px-5">            
          <Link href="/" className=' hover:opacity-80'>
              <span className="flex flex-shrink-0 items-center text-3xl"><h1>Experience ISU!!</h1></span>
          </Link>
        </nav>
      </header>
      <main className="border overflow-auto scroll-smooth snap-y snap-mandatory h-full w-full py-5"> 
        <TextSection text="Enjoy!!"/>  
        {data.map( (a, i) => <Section key={i} item={a}/> )}
        <TextSection text="Thank you!!" subtext="Email joo@iastate.edu for others"/>  
      </main>
    </>
  )
}

function Section({ item }){
  return(
    <div className=' snap-always snap-center w-cust-wd-75 md:w-cust-wd-60  h-auto flex-shrink-0 relative border-2 border-gray-200 rounded-3xl mx-auto my-20 p-0'>
      <NextImage src={item.image} width="500" height="500" className="rounded-3xl" alt={item.title} sizes="100vw" style={{ width: '100%', height: 'auto', }}/>
      <Text text={item.description} />
    </div>
  )
}


function TextSection({ text, subtext }){
  return(
    <div className='snap-always snap-center w-cust-wd-75 h-cust-ht-75 md:w-cust-wd-60 flex-shrink-0 relative border-2 border-gray-200 rounded-3xl mx-auto my-20 p-0 text-center'>
      <div className='relative flex flex-col items-center justify-center w-full h-full'>
        <span className='text-9xl'>{text}</span>
        <span className='text-xl'>{subtext}</span>
      </div>
    </div>
  )
}
 